version: '3.7'
services:
        db:
                image: postgres:11.5-alpine
                environment:
                        - POSTGRES_PASSWORD=${DB_PASS}
                        - POSTGRES_USER=${DB_USER}
                        - POSTGRES_DB=${DB_NAME}
                ports:
                        - ${DB_HOST}:${DB_PORT}:5432
                volumes:
                        - ./tmp/postgres:/var/lib/postgresql/data
